apiVersion: v1
kind: PersistentVolume
metadata:
  name: tytanis-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: tytanis-disk
    fsType: ext4
