apiVersion: v1
kind: Pod
metadata:
  name: tytanis-files
spec:
  containers:
  - name: tytanis-files
    image: eu.gcr.io/bigdata-1275/tytanis-files:2.0
    volumeMounts:
            - name: tytanis-persistent-storage
              mountPath: /var/lib/tytanis/db
  nodeSelector:
    failure-domain.beta.kubernetes.io/zone: europe-west1-d
  volumes:
      - name: tytanis-persistent-storage
        gcePersistentDisk:
          pdName: tytanis-disk
          fsType: ext4
  restartPolicy: Never